default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  timeout: 5000
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: mkdev_dev

test:
  <<: *default
  database: mkdev_test

production:
  <<: *default
  database: mkdev_prod
