default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 12345
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: mkdev_dev

test:
  <<: *default
  database: mkdev_test

production:
  <<: *default
  database: mkdev_prod
